---
###############################################################
#                   Authelia Configuration                    #
###############################################################

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
jwt_secret: a_very_important_secret

default_redirection_url: http://localhost

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: localhost
      policy: one_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: unsecure_session_secret
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: localhost  # Should match whatever your root protected domain is
  # IMPORTANT: Set to false for development (HTTP)
  # Set to true for production (HTTPS)
  secure: false

storage:
  encryption_key: 8d8652a72a82f50058d15976baa55f1b
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt