server:
  address: tcp://0.0.0.0:9091

log:
  level: debug

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    - domain: "traefik.local"
      policy: one_factor
    - domain: "auth.local"
      policy: bypass

session:
  name: authelia_session
  expiration: 1h
  inactivity: 5m
  cookies:
    - domain: local
      authelia_url: http://auth.local
      default_redirection_url: http://traefik.local

storage:
  redis:
    address: tcp://authelia-redis:6379

notifier:
  filesystem:
    filename: /config/notification.txt

identity_validation:
  reset_password:
    jwt_secret: "a_very_secret_string_for_jwt"