http:
  routers:
    authelia:
      rule: "Host(`auth.local`)"
      entryPoints:
        - web
      service: authelia

  services:
    authelia:
      loadBalancer:
        servers:
          - url: "http://authelia:9091"

  middlewares:
    authelia:
      forwardAuth:
        address: http://authelia:9091/api/verify?rd=http%3A%2F%2Fauth.local%2F
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
